### ISSUE TITLE
ON/OFF button

### ISSUE THREAD

**Issue by shprink** [kortaggio/HideNewsFeed#3]
Can't find an extension that does that. I want to turn the extension OFF sometimes without having to disable it.

**Comment by billmei** [comment]
Where would this button live?

**Comment by shprink** [comment]
In the contextual menu? Right click

**Comment by billmei** [comment]
My view is, the purpose of the extension is to prevent you from getting distracted too easily. If we put an on/off button in the context menu it becomes too easy to turn the extension off, therefore defeating the purpose which is to prevent you from getting distracted.

**Comment by shprink** [comment]
It is up to you. If I do not want to get distracted I do not use FB at all.
The only way I use this extension or another is if it has a ON/OFF button
so I can turn it ON during my working hours and turn it OFF afterwards.

Julien Renaux
Software Engineer
Blog http://julienrenaux.fr/ - Twitter https://twitter.com/julienrenaux
- Hire me on Toptal
  http://www.toptal.com/resume/julien-renaux#select-just-supreme-hackers

**Comment by billmei** [comment]
Interesting, you're the first person who's expressed a need for separation between a work context and a personal context. Again, I won't implement an on/off button in the popover menu because as I mentioned it makes it too easy to get distracted. One workaround for you if you want the extension to automatically be on during work hours and off during non-work hours, is to install the extension in your personal Google Chrome profile, and leave the extension uninstalled in your work Google Chrome profile. That way, you can use the [switch person](https://support.google.com/chrome/answer/2364824) functionality in Chrome to separate your work profile from your personal profile, which should also separate extensions.

**Comment by shprink** [comment]
Thanks very much and no worries.
